import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css', 
                    'resources/js/app.js',
                    'resources/css/calendar.css', 
                    'resources/css/configuraciones.css', 
                    'resources/css/clases-socio.css', 
                    'resources/css/configuraciones.css', 
                    'resources/css/globals.css', 
                    'resources/css/inicios.css',
                    'resources/css/pagos.css',
                    'resources/css/sidebar-menu.css', 
                    'resources/js/asistencia.js', 
                    'resources/js/bootstrap.js', 
                    'resources/js/clases-gestion.js', 
                    'resources/js/clases-misclases-profe.js', 
                    'resources/js/clases-socio.js', 
                    'resources/js/clases.js', 
                    'resources/js/configuraciones.js', 
                    'resources/js/ejercicio.js', 
                    'resources/js/ingresoGym.js', 
                    'resources/js/inicio-admin.js', 
                    'resources/js/inicio-administrativo.js', 
                    'resources/js/inicio-profesor.js', 
                    'resources/js/inicio-socio.js', 
                    'resources/js/membresias-socio.js', 
                    'resources/js/membresias-administrativo.js', 
                    'resources/js/pagos-admin.js',
                    'resources/js/pagos-socio.js',
                    'resources/js/profesores-administrativo.js', 
                    'resources/js/profesores-socio.js', 
                    'resources/js/rutina.js',
                    'resources/js/salas.js',
                    'resources/js/sidebar-menu.js', 
                    'resources/js/socio.js', 
                    'resources/js/usuario.js', 
                    'resources/js/validarPerfil.js'],
            refresh: true,
        }),
        tailwindcss(),
    ],
});
